# Generated by Django 3.2.25 on 2025-01-17 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0004_alter_photo_photo'),
    ]

    operations = [

    ]
